#!/bin/bash
javac CaesarComparer.java

echo "Timing for encryptTwo method:"
time java -Djava.compiler=NONE CaesarComparer encryptTwo
echo "Timing for encrypt method:"
time java -Djava.compiler=NONE CaesarComparer encrypt
